name: Node CI

on:
  - push

jobs:
  checkCodestyle:

    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v1
      
      - name: Run linter
        run: make lint
